version: '2'
template:
  name: Upgrade to Toolchain
  description: |2-
     A toolchain is an open, extensible system of tools that supports the development, deployment, and operations of an application.


    #### About the Upgrade Process
     When you create this toolchain, it is preconfigured with GitHub for source control, Delivery Pipeline for building and deployment, and the Eclipse Orion Web IDE for code editing. You can add more tools to the toolchain as needed. To get started, click **Create**.


    #### More Info
     [Tutorial: Upgrade your project to a toolchain](https://ibm.biz/ids-upgrade-blogpost)

     [Docs: Getting started with Continuous Delivery](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/index.html)

     [Blog: Bluemix Continuous Delivery](https://www.ibm.com/blogs/bluemix/2016/11/bluemix-continuous-delivery-is-now-live/)
     
  header: '![](toolchain.svg)'
  required:
    - repo
toolchain:
  template:
    v1-projectId: '{{projectId}}'
    scheduledDate: '{{scheduledDate}}'
    v1-pipelineStages: '{{v1PipelineStages}}'
    getting_started: >-
      This toolchain was created from your [DevOps Services
      project]({{projectUrl}}). Before you start to use the toolchain, complete
      a few [next
      steps](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/upgrade_projects.html#upgrade_next_steps).
      To learn more about toolchains, see [Getting started with Continuous
      Delivery](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/index.html?pos=2).
  name: '{{projectName}}'
  generator: migration-engine
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{projectName}}'
      repo_url: '{{projectRepoUrl}}'
      type: link
      has_issues: true
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{projectName}}'
      v1-projectId: '{{projectId}}'
      configuration:
        content: '{{pipelineContent}}'
        execute: false
        env:
          REPO: repo
        source:
          version: v1
          environment: '{{pipelineEnv}}'
          pipelineUrl: '{{pipelineUrl}}'
          projectUrl: '{{projectUrl}}'
          showLink: true
  webide:
    service_id: orion
form:
  githubpublic:
    parameters:
      repo_url: '{{projectRepoUrl}}'
      existing_repo_url: '{{projectRepoUrl}}'
      enable_traceability: false
    schema:
      $ref: github.json
